# Generated by Django 2.1.7 on 2019-04-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateAttribute',
            fields=[
                ('GA_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Graduate Attribute',
                'managed': True,
                'default_permissions': 'view',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('course_number', models.CharField(max_length=9)),
                ('course_title', models.CharField(max_length=50)),
                ('assessment_method', models.CharField(max_length=60)),
                ('level', models.CharField(help_text='Enter I, D, or A: (I)ntroduced, (D)eveloped or (A)pplied', max_length=1)),
                ('bins', models.CharField(help_text='Enter bin ranges in comma-separated values', max_length=20)),
                ('GA', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indicators.GraduateAttribute')),
            ],
            options={
                'verbose_name': 'Indicator',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='DEFINE', max_length=50)),
            ],
            options={
                'verbose_name': 'Program',
                'managed': True,
                'default_permissions': 'view',
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indicators.Program'),
        ),
    ]
